### ISSUE TITLE
FR: revset function(s) to singularize revisions (maybe `first(...)` to start with)

### ISSUE THREAD

**Issue by avamsi** [martinvonz/jj#1110]
This could be useful with commands like rebase that only take a single revision -- for example,

```
$ jj rebase -b 'first(remote_branches("", origin).. ~ empty())' -d main
```

**Comment by yuja** [comment]
What do you expect to be the first with that revset?

I considered adding `first()` or `limit()` before, but rejected my idea because the order of revsets seemed to be implementation detail in jj, and the visible order could also be affected by #242.

It might be better to specify the sorting order explicitly (e.g. `latest()` to pick the first element in committer-timestamp order.)

**Comment by avamsi** [comment]
Makes sense, first was just the first singularizing function I could think of 😅 -- `latest(...)` might be even better for the rebase workflow I was thinking of (more often than not, I would probably be okay with just rebasing the latest commit I'm working on, leaving any older ones untouched).

Also, I just realized, the rebase example in my first comment should probably be more like the one below (exclude main: so that the command is repeatable) --

```
$ jj rebase -b 'latest(remote_branches("", origin).. ~ (main: | empty()))' -d main
```
