### ISSUE TITLE
`jj init --git-repo` fails and leaves broken .jj folder, when the location doesn't contain a .git

### ISSUE THREAD

**Issue by tp-woven** [martinvonz/jj#1305]
## Steps to Reproduce the Problem

1. Navigate to a folder that doesn't have a `.git`.
1. Run `jj init --git-repo=.`.

## Expected Behavior
No `.jj` folder created in the directory (or `.jj` directory is cleaned up).

## Actual Behavior
`.jj` directory is created, but is unusable.

**Comment by kevincliao** [comment]
Hi, I'm new to jj and Rust, and am looking into this issue to get familiar to the codebase.

The problem seems to be that right after [create_jj_dir](https://github.com/martinvonz/jj/blob/81aa90efd360777c1a59c072a4cb6bad280021d9/lib/src/workspace.rs#L167), ReadOnlyRepo::init calls the backend factory, which calls [git2::Repository::open().unwrap()](https://github.com/martinvonz/jj/blob/81aa90efd360777c1a59c072a4cb6bad280021d9/lib/src/git_backend.rs#L83) and panics when the directory does not exist, leaving an unfinished jj directory.

One solution is to update the functions in the call chain to return an error instead of unwrapping, so we can catch the error and delete the unfinished jj directory. This includes:
- translating git2::Error to BackendError, and updating [init_external](https://github.com/martinvonz/jj/blob/81aa90efd360777c1a59c072a4cb6bad280021d9/lib/src/git_backend.rs#L76) to return Result<Self, BackendError> instead of Self
- To propagate the error, update ReadOnlyRepo::init to return a new error type RepoInitError instead of PathError
```
#[derive(Error, Debug)]
pub enum RepoInitError {
    #[error(transparent)]
    Backend(#[from] BackendError),
    #[error(transparent)]
    Path(#[from] PathError),
}
```
- translate RepoInitError to WorkspaceInitError in [init_with_factories](https://github.com/martinvonz/jj/blob/81aa90efd360777c1a59c072a4cb6bad280021d9/lib/src/workspace.rs#L170).

Does this look ok or am I on the wrong direction?

**Comment by martinvonz** [comment]
Yes, that all sounds good to me. Thanks!
