### ISSUE TITLE
[submodules] Design on-disk format for Git submodules

### ISSUE THREAD

**Issue by chooglen** [martinvonz/jj#1403]
This should answer:

- How submodule commits are stored.
- Whether submodules should have jj repo features (a commit index, operation log)
- How submodules will be represented in the working copy.

Some requirements to consider are:

- What features need to be supported (largely depends on https://github.com/martinvonz/jj/issues/1402)
- How to fetch/push submodules from/to remotes.
- How submodules will work in a colocated repo.
- How to support garbage collection.

**Comment by martinvonz** [comment]
> * How submodule commits are stored.
> * Whether submodules should have jj repo features (a commit index, operation log)

I suspect it will be easiest to store them as full jj repos somewhere inside the top-level `.jj/repo/` directory.

> * How submodules will be represented in the working copy.

I would start by storing them in the working copy as regular directories (maybe with a `.git/` if we want to help the co-located case) and recorded in the working-copy state file as a new variant. Oh, we already have [a variant for `GitSubmodule`](https://github.com/martinvonz/jj/blob/d9a5869bcd41c640c797f0bad79ec1039cdc2add/lib/src/working_copy.rs#L48-L53), but we'd might need to extend that with some metadata. The idea is that we'd look at that when snapshotting the directory and we propagate it up to the superproject as a commit instead of a tree as we normally would for a regular directory.

> * How to fetch/push submodules from/to remotes.

My current feeling is that something like `jj --submodule path/to/submodule git push` should work.

**Comment by chooglen** [comment]
Closed by https://github.com/martinvonz/jj/pull/1482
