### ISSUE TITLE
FR: `jj branch rename`

### ISSUE THREAD

**Issue by arxanas** [martinvonz/jj#1457]
It seems that there is currently no command to delete an existing branch pointing to a commit and create a new branch pointing to that same commit in one operation, which sounds occasionally useful. Or is there some way to use `jj branch set` or another command to accomplish this?

**Comment by martinvonz** [comment]
I think it makes sense to have that command even though it's easy to create a shell alias for it.

**Comment by essiene** [comment]
I'd like to take a stab at this if no one else is working on it.

**Comment by essiene** [comment]
I have a draft PR at https://github.com/martinvonz/jj/pull/2699.

It's not yet ready for a full review as I still need to read to docs to ensure I have followed all the steps in creating a PR properly.

But any initial review comments would be helpful to me.

Thanks!

**Comment by arxanas** [comment]
Does the branch rename also update Git's branch metadata (such as the remote-tracked branch)? This information is contained in the `.git/config` file instead of the ref itself. (If we use libgit2, then it might already be handled, depending on exactly how we do it.)

**Comment by yuja** [comment]
> Does the branch rename also update Git's branch metadata (such as the remote-tracked branch)? 

It doesn't, and I don't think we can implement that properly because remote-tracking branch should have the same name in jj. Perhaps, jj can issue a warning if the renamed branch had a tracking remote.

**Comment by essiene** [comment]
I'll follow up with PR to issue a warning if the old branch has a remote branch.

**Comment by essiene** [comment]
Checking my understanding of the comments from @arxanas and @yuja...

If the `jj` branch has a remote branch (git or eventually other), ideally we would like to rename that branch as well. If we can't we should issue a warning, so the user knows to do this manually.

Also, IIUC, in `jj`, local and remote branches always have the same name(?).

I found [repo.rename_remote()](https://github.com/martinvonz/jj/blob/c5f76d6b4d707cc401897f05a27a086662da7efe/lib/src/repo.rs#L1122) which seems to rename remote branches. What does that do? Will it update the git remote branch name, such that at the next push, the old remote branch is deleted while the new remote branch is created?

Or maybe I could call [repo.{get,set}_remote_branch()](https://github.com/martinvonz/jj/blob/main/lib/src/repo.rs#L1077-L1085) directly? They return/take a RemoteRef instead of RefTargets. Would calling these do the correct rename behaviour for remotes?

I see a [repo.has_branch()](https://github.com/martinvonz/jj/blob/main/lib/src/repo.rs#L1046-L1050) but it returns true for either local or remote branch existence. Would it make sense to add a `has_remote_branch` instead?
 
Sorry for the slew of questions, some of which probably don't make sense ;-). I don't yet correctly understand the git side of things, though this should work across different backends.

Thoughts?

**Comment by essiene** [comment]
Post holiday follow up! :-D

Thanks. This all makes better sense now. I'll send a PR shortly.
