### ISSUE TITLE
Error "invalid charset name" for many operations

### ISSUE THREAD

**Issue by EyeCon** [martinvonz/jj#1496]
## Description

jj 0.7.0 doesn't like my charset for some reason.

## Steps to Reproduce the Problem
On my computer (Win10, with cmd but I also tried Powershell), almost all operations give the error message "invalid charset name":
```
C:\Users\EyeCon>cd \temp1

C:\temp1>jj --version
jj 0.7.0

C:\temp1>mkdir jjtest1

C:\temp1>cd jjtest1

C:\temp1\jjtest1>jj init --git
Initialized repo in "."

C:\temp1\jjtest1>jj st
invalid charset name

C:\temp1\jjtest1>jj op log
invalid charset name

C:\temp1\jjtest1>jj abandon
Abandoned commit e9634d7bf8c1 (no description set)
Working copy now at: dffddd360787 (no description set)

C:\temp1\jjtest1>jj commit -m "Test1"
Working copy now at: 7f8e9557f894 (no description set)

C:\temp1\jjtest1>jj log
invalid charset name

C:\temp1\jjtest1>chcp
Active code page: 65001

C:\temp1\jjtest1>type c:\Users\EyeCon\.jjconfig.toml
[user]
name = "Eye Con"
email = "jj.speq@erine.email"

C:\temp1\jjtest1>jj help
invalid charset name
```

## Expected Behavior
That the commands `st`, `log`, `op log`, `help` work without errors

## Actual Behavior
Error "invalid charset name"

## Specifications

- Platform: Win10 22H2 Build 19045.2728
- Version: jj 0.7.0

**Comment by martinvonz** [comment]
Thanks for the report. We set an `LESSCHARSET=utf-8` environment when we call the `less` pager. Maybe your version of `less` doesn't support it? Try adding a `ui.pager = "less -FRX"` to your `~/.jjconfig.toml` and see if that helps.

**Comment by EyeCon** [comment]
`less` itself seems to work:

```
C:\temp1\jjtest1>less
Missing filename ("less --help" for help)

C:\temp1\jjtest1>less --help
# (Shows help)

C:\temp1\jjtest1>less --version
less 340
Copyright (C) 1999 Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of less under the terms
of the GNU General Public License.
For more information about these matters,
see the file named COPYING in the less distribution.

C:\temp1\jjtest1>less c:\Users\EyeCon\.jjconfig.toml
# (Shows the file)
```

But my `less` doesn't like those options. After changing the config as indicated:

```
C:\temp1\jjtest1>type c:\Users\EyeCon\.jjconfig.toml
[user]
name = "Eye Con"
email = "jj.speq@erine.email"

[ui]
pager = "less -FRX"

C:\temp1\jjtest1>jj log
There is no -F option ("less --help" for help)
```

...so I'm undoing the change for now.

**Comment by EyeCon** [comment]
But it seems to be the source of the problem indeed:

```
C:\temp1\jjtest1>set LESSCHARSET=utf-8

C:\temp1\jjtest1>less c:\Users\EyeCon\.jjconfig.toml
invalid charset name
```

**Comment by martinvonz** [comment]
See if you can upgrade to a new version of `less`, or maybe install a different pager (I have no idea which ones are available for Windows). Since your current version doesn't support `-F`, try adding that `ui.pager` line but maybe without `-F`, and maybe without `-R` and `-X` too, if `less 340` doesn't support them (`ui.pager = "less"` should work).

**Comment by martinvonz** [comment]
According to http://www.greenwoodsoftware.com/less/old.html, your `less` is from 1999, so it is probably time to upgrade :)

**Comment by EyeCon** [comment]
I rarely use Windows for development, so combined with some laziness it's no wonder :)

Just upgraded to the latest version. Now it works. Sorry, my bad for using ancient utils.

**Comment by martinvonz** [comment]
No problem. I think we can assume that your setup was unusual for now, but let's see if we get more reports of the problem. I'm not sure what we would do if that happens :)

**Comment by necauqua** [comment]
Well hard-depending on less like that (by default) seems slightly brittle, we can detect if recent enough less is present and if not print without pager (with a hint to install less or update the config maybe)

**Comment by martinvonz** [comment]
We do print a warning if the configured pager is not found, but we don't have any special handling of old versions of `less`. I'm a little hesitant to check the version of `less` before starting it since it's going to be wasted in 99.9% of cases or something, even if it only wastes a few ms or something. We could change the default on Windows to not pass `$LESSCHARSET` if we determine that running very old versions of `less` is somewhat common there. (I am a little curious where you got your old `less` binary from, @EyeCon.)

What makes it extra confusing is that when `less` doesn't understand the charset, it seems just prints that error and doesn't fall back to a default charset.

By the way, I didn't find a mention of "LESSCHARSET" in either Git or Mercurial.

**Comment by EyeCon** [comment]
That's actually from an old version of [UnxUtils](https://sourceforge.net/projects/unxutils/).

**Comment by Ralith** [comment]
The robust thing to do here would be, on Windows, bundle our own less binary and point the default configuration at it.
