### ISSUE TITLE
FR: `swap` command (better tools for reordering commits part 1)

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#1530]
A swap command could have the obvious UI: `jj swap rev1 rev2`. I'm not sure if we can do better than:

- Both revsets have to resolve to single revisions
- The parents of `rev1` will be whatever the parents of `rev2` were. This behavior would be a bit confusing for empty merge commits (which are common), so I'd disallow merge commits by default and have an option to enable it.

In terms of implementation, this is related to https://github.com/martinvonz/jj/issues/1188.

This is a baby version of #1531.

**Comment by dbarnett** [comment]
Instead of creating two different command names, could one command do both if you support a non-interactive variant of `reorder` under the same command name? Initially you could support whatever special case operations are easiest and reject attempts to do anything else.

Personally if I had a full `reorder` command I'd just forget `swap` every existed and consider it clutter.

**Comment by ilyagr** [comment]
Yes, the more I think of it the less attractive it becomes. What you really want, usually, is to move a commit to before/after another commit. Martin pointed that out in https://github.com/martinvonz/jj/issues/1188#issuecomment-1416682924.
