### ISSUE TITLE
Specify the naming or prefix for the `jj git push --change xxx`

### ISSUE THREAD

**Issue by lazywei** [martinvonz/jj#1958]
Hi,

I've been using sapling and now trying to do the similar thing as push stack. I followed the docs and run commands like
```
jj git push --change XXX --change YYY
```

However, the created branch is with naming like
```
push-otznykxnuusx
push-vlxzuutruspk
```

My questions are:
1. Is it possible to specify the naming with the `--change` flag?
2. Or is it possible to specify a template, like `<username>/push-xxxxxx`, to make it easier to work in a collaborated repo?
3. Since we need to manually specify the base branch when creating the stack PRs with this method, is it possible to add some sort of ordinal naming like `push-42-otznykxnuusx` or `push-pr42-otznykxnuusx` so it's easier to spot out the ordering of multiple created branches / PRs?

Thanks!

**Comment by thoughtpolice** [comment]
Quick reply while I'm finishing some stuff up and just checking GH Issues:

1. You can create a normal branch name with `jj branch create <name> -r <rev>`, then `jj git push --branch <name>` instead. By default `--change` will automatically make that name based on the change ID.
2. I don't think so, as of right now. But in practice I haven't found it an issue while working on the `jj` repo with others.
    - For example, I just `jj git push -c <id>` and it creates a `push-<id>` branch on this repo. I make a PR, then when I go back to it, I just copy/paste the branch name from the PR, at the top of the page, on GitHub. Because multiple developers use the repo this way, I can just copy/paste those `push-xyz` IDs from any branch and checkout anyone else's work.
    - So in other words, you just stop worrying about the branch name, and look it up on demand when you actually open the PR. For example, when viewing #1541, I would just click the branch name at the top, which copies it into my clipboard <img width="794" alt="image" src="https://github.com/martinvonz/jj/assets/3416/947004e6-34c9-4f5a-b199-c7108689e782">
    - This is pretty GitHub specific, but at least I know @martinvonz and I both push changes and branches this way directly into this repo
    - Not everyone does though! @ilyagr and @arxanas seem to name their branches explicitly.

3. I'm not sure. In practice I tend to submit multiple `--change`s at once and encourage people to just read the individual commits. This is partially GitHub's problem because there isn't a neat way to make PRs from PRs, unless you have write access to the repo. And there's honestly still a bunch of open questions we have about tracking open PRs, what commits should be shown/should not be shown by default, etc. Probably @martinvonz or maybe @ilyagr can speak more about this.

Hope this helps.

**Comment by martinvonz** [comment]
(I bit duplicated with the answer above because I had almost finished before I saw it.)

> * Is it possible to specify the naming with the `--change` flag?

No. We have talked about doing that but it would require two arguments (for the branch name and the revision), so we're not sure if that means it's better to add a `jj git push-branch` or something instead of making `jj git push`'s syntax complicated.

> * Or is it possible to specify a template, like `<username>/push-xxxxxx`, to make it easier to work in a collaborated repo?

Yes, you can set something like `push.branch-prefix = "lazywei/push-"` in your config file. I'll send a PR to document that in https://github.com/martinvonz/jj/blob/main/docs/config.md

> * Since we need to manually specify the base branch when creating the stack PRs with this method, is it possible to add some sort of ordinal naming like `push-42-otznykxnuusx` or `push-pr42-otznykxnuusx` so it's easier to spot out the ordering of multiple created branches / PRs?

Good question. We have #485 about adding more specialized support for setting the base branch in GitHub. Until then - or even after, when pushing a forge we don't support - I would suggest manually naming branches with `jj git branch create`. Then you can use `jj git push -r main..@` or something like that to push all branches in that range of commits. You can use `jj log -r main..@` first to verify that it's the range you want.

**Comment by arxanas** [comment]
> Not everyone does though! @ilyagr and @arxanas seem to name their branches explicitly.

I would name them automatically, but I don't use `jj git` and I don't have other automation at present to name the branch for me. I do prefer to prefix the branch with my username (`arxanas/<branch>`) so that it's associated with me and other tooling can neatly collapse/hide my branches.
