### ISSUE TITLE
Convert `root` revset symbol to a function?

### ISSUE THREAD

**Issue by martinvonz** [martinvonz/jj#2095]
By converting `root` to a `root()` function, we don't have to have to worry about conflicts with change id prefixes, and we enable the user to name their branches `root` without running into problems.

**Comment by ilyagr** [comment]
I'm on the fence here, though I'm leaning towards this since it makes things more consistent.

I'm slightly unhappy that `root()::` and `root()::@` will then need quoting in the shell.

OTOH, the user can always make a revset alias without parentheses. I wonder, with the current implementation, would it be allowed to make a revset alias `root="root()"`? Do we want it to be allowed (I'm leaning towards yes)? Also, should a branch `root` override such an alias?

**Comment by yuja** [comment]
I'm for `root()`. I don't think it's frequently used, so less magic is better. And if we made `@` a syntactic node, there would be no reserved symbols.

>  would it be allowed to make a revset alias `root="root()"`?

Yes. You can even define `main='present("main") | present("master")'` though it's a black magic.

> should a branch root override such an alias?

I would say no. Branch names are more volatile than user configuration.

**Comment by ilyagr** [comment]
That sounds good. I wonder about two minor points:

> And if we made @ a syntactic node...

What does this mean? What difference would it make?

> Branch names are more volatile than user configuration.

I don't feel strongly about this at all, but I didn't follow your reasoning. It seems to me that if branch names are more volatile, they should override user configuration. Otherwise, how will you address a branch with a weird name?

**Comment by yuja** [comment]
> > And if we made @ a syntactic node...
> 
> What does this mean? What difference would it make?

`"@"` (quoted) would be resolved to a branch or tag named `@` whereas `@` is the working copy. And we'll need to use `"branch name with whitespace"@remote` instead of `"branch name with whitespace@remote"`.

Downside is that `author("foo@example.org")` would require quoting.

> > Branch names are more volatile than user configuration.
> 
> I don't feel strongly about this at all, but I didn't follow your reasoning. It seems to me that if branch names are more volatile, they should override user configuration.

I mean it wouldn't make sense if user-configured alias suddenly got overridden after `jj git fetch`.

**Comment by ilyagr** [comment]
> `"@"` (quoted) would be resolved to a branch or tag named `@` whereas `@` is the working copy. And we'll need to use `"branch name with whitespace"@remote` instead of `"branch name with whitespace@remote"`.
> 
> Downside is that `author("foo@example.org")` would require quoting.

All of this sounds good to me. I hadn't realized you don't currently need to quote an email address.

> I mean it wouldn't make sense if user-configured alias suddenly got overridden after `jj git fetch`.

I see. If we go with this (aliases override branches), we'll probably be able to eventually come up with some syntax for the user to specify that they want the branch. I'm not sure what the best option is, but the first ones that come to mind are `"branch"` instead of `branch`, or `literal:branch`. Considering that you can always use the change id, I don't feel this needs to be rushed in any way either.

**Comment by yuja** [comment]
> we'll probably be able to eventually come up with some syntax for the user to specify that they want the branch.

`"branch"` works now since string literal isn't substituted by alias. Another one is `branches(literal:branch)` which explicitly selects branch by name (but no error if `branch` doesn't exist.)

**Comment by avamsi** [comment]
(Not related to this issue itself) On the subject of less magic, any thoughts on making argument parsing stricter? For example, don't allow `branches(literal:main)` (should instead be `branches(literal:"main")`).

**Comment by yuja** [comment]
> don't allow `branches(literal:main)` (should instead be `branches(literal:"main")`).

Does that also mean a string argument (not in a set expression context) should always be quoted?
(e.g. `author("foo")`, not `author(foo)`)

I'm fine with that, but it might be a bit annoying on Windows where command arguments are usually double-quoted iirc.

**Comment by avamsi** [comment]
> Does that also mean a string argument (not in a set expression context) should always be quoted?
(e.g. author("foo"), not author(foo))

Yep, that's what I was thinking.

> I'm fine with that, but it might be a bit annoying on Windows where command arguments are usually double-quoted iirc.

ACK, maybe the string arguments could use single quotes in that case? (Filed #2101 to not side track this issue.)
