### ISSUE TITLE
FR: Is it possible to make the auto anonymous working copy commit optional and configurable?

### ISSUE THREAD

**Issue by cloudhan** [martinvonz/jj#2358]
**Is your feature request related to a problem? Please describe.**
Currently the working copy will be automatically committed to an anonymous commit, this is drastically different from git workflow. With jj, it becomes a subtractive process on making commit, wheraes the git one is additive.

**Describe the solution you'd like**
Make it configurable.

**Additional context**
This create some friction of my adopting jj. Before I fully evaluate it, I don't want to fully commit to it yet. I am currently using git-branchless and it works like a charm, and I heard that jj provides some advance feature, I want to give it a try, but just I don't want to change my workflow.

**Comment by cloudhan** [comment]
Welp, the skip^n mgr said if you commit credential to the repo, then you are not eligible for promotion in the next fiscal year 😅. As jj and git branchless have already automated many process, the subtractive part is extremely suspicious to me.

**Comment by martinvonz** [comment]
Did you considering trying jj in a throw-away clone of your repo?

Besides the risk of persisting credentials, is your main concern that you'll be wasting disk space?

To answer your question directly: I don't think it makes much sense to add a config option. That would be equivalent to having a config option to git that prevented committing. I.e., you would have a read-only repo then.

**Comment by cloudhan** [comment]
I mean, I want to

```bash
jj new ...
# edit <some file>
jj add <some file> # update the current commit manually, 
                   # this effectively disable the anonymous working copy commit completely,
                   # and leave it to user. Whether updating the current commit or a staging area is an open question.
# no split needed, move on
```

Manually add file to the commit I am working on, instead of automatical updating.

```bash
jj new
# edit <some file> and the working copy is tracked automatically
jj split ... # and then move on
```

> is your main concern that you'll be wasting disk space

not main concern, but disk space wasting is definitly a thing.

**Comment by martinvonz** [comment]
You can emulate the git workflow by replacing `git checkout X` by `jj new X -m "staging area" && jj new` and `git add -p` by `jj squash -i`. That might be an interesting way to transition from git. I think you'll quickly get tired of having a separate staging area, but who knows.

**Comment by cloudhan** [comment]
More precisely speaking, it is not about revert to the git workflow, it is about additive vs substractive. How to achieve the additive workflow is another question. And the title is misleading.

With additive workflow, I selectively add my change to the repo. The unfinished files and dirty working directory is not managed by jj.

With substractive workflow. I selectively pick my change from the managed working copy commit with `split`.

**Comment by thoughtpolice** [comment]
This is morally the equivalent, I guess, of running `--ignore-working-copy` with every command. But I think this request probably goes a little too "against the grain" of the current design philosophy in several important ways, and making it a feature is unlikely.

The additive-vs-subtractive metaphor is helpful, but there are more subtle consequences to the "snapshot" model we use today that go beyond simple workflow changes. There are large design ramifications. For instance, in your example, what if you ran `jj new` again after you edited the file but *before* you ran `jj add`? Today `jj` simply takes a snapshot first and then switches states trivially. But now the "dirty working tree" case needs to be handled specifically, because the file you modified won't be snapshotted. Do you reject all uses of `jj new` until the file is recorded? Only allow it for commits that don't conflict? What if a conflict does happen? These need to be addressed. There are probably many such cases with every command, now.

Overall, many operations that would leave the tree in potentially "unsafe" or indeterminate states with other tools are trivially safe with `jj` thanks to the snapshot model. I've come to appreciate the simplicity of the snapshot model, since it makes all operations ones that work on commits. I don't think we should encourage people to shy away from it; we probably have to accept (and tell users!) that some workflow fundamentals have to change.

> said if you commit credential to the repo, then you are not eligible for promotion in the next fiscal year 😅.

FWIW, this is definitely a huge problem. :) The biggest problem with this is that:

- `jj` doesn't garbage collect the operation log, so those commits hang around
- In the future, with some kind of source control server, you may send those changes to the upstream system when a snapshot happens

I don't know what to think about number 2, but number 1 is definitely something that people are aware of, though a tracked issue to implement oplog gc currently escapes me and might not be filed. But it's been discussed in relatively recent memory...
