### ISSUE TITLE
FR: Add an option "jj rebase --skip_empty" or similar

### ISSUE THREAD

**Issue by matts1** [martinvonz/jj#2588]
**Is your feature request related to a problem? Please describe.**
When you rebase commits that have been squashed, you end up with empty commits.
I always have to follow up `"jj rebase -s 'all:(children(IMMUTABLE) & ~IMMUTABLE)' -d main@origin"` with `jj abandon 'empty() & ~IMMUTABLE & ~merges()`.

**Describe the solution you'd like**
Git rebase has "--empty=drop|keep|ask". I imagine a similar solution would work just fine for jj

**Describe alternatives you've considered**
I currently run `jj abandon 'EMPTY` after rebasing every time

**Additional context**

**Comment by matts1** [comment]
Happy to assign this to myself, looking at the code it doesn't look too hard

**Comment by martinvonz** [comment]
Sounds like a duplicate of #229?

**Comment by matts1** [comment]
API clarification: Should I make it `--empty=drop` or `--skip-empty`?

`--empty=drop` would allow us to later do `--empty=ask`, which I have mixed feelings about. Rebases should always succeed in JJ, so I'm tempted to go with `--skip-empty`, but I saw a FR for `jj rebase --interactive`, where it might make sense to actually ask.

**Comment by martinvonz** [comment]
I agree that we should not make it interactive. What's the FR for `jj rebase --interactive`? #1531? Even if we have an initial interactive phase in that command where you reorder commits etc., I think the rest of it should just execute the request plan non-interactively.

Regarding the exact name, do you think we should even call it `--skip-emptied` instead of `--skip-empty` to clarify that already empty commits will not be skipped? Or should we drop already empty commits too (maybe we should continue on #229)? Also, should it be "skip" or "abandon"?

**Comment by matts1** [comment]
As you said, dup of #229, we can continue discussions there
