### ISSUE TITLE
"The packed-ref transaction could not be committed" when trying to delete packed refs on Windows

### ISSUE THREAD

**Issue by jennings** [martinvonz/jj#2697]
## Description

Sometime between 0.11.0 and 0.12.0, jj stopped being able to delete refs that have been packed in the colocated Git repo.

The root cause seems to be a PermissionDenied error when trying to rename packed-refs.lock to packed-refs. Adding a `dbg!(err)` to `delete_git_ref()` gave this output:

```
[lib\src\git.rs:810] err = FileTransactionCommit(
    PackedTransactionCommit(
        Commit(
            Error {
                error: Os {
                    code: 5,
                    kind: PermissionDenied,
                    message: "Access is denied.",
                },
                instance: File {
                    inner: Handle {
                        id: 0,
                        _marker: PhantomData<gix_tempfile::handle::Writable>,
                    },
                    lock_path: "\\\\?\\C:\\src\\SNIP\\.git\\packed-refs.lock",
                },
            },
        ),
    ),
)
```

Process Monitor show that a read handle to packed-refs was still open when the rename was attempted.

- [Discord discussion](https://discord.com/channels/968932220549103686/1182759794877149317)

## Steps to Reproduce the Problem

```powershell
PS> git version
git version 2.42.0.windows.2

PS> jj version
jj 0.12.0-90e241cc9593e630c6a58e87559669896bf3926e

PS> git init repo
Initialized empty Git repository in C:/src/jj-pr/repo/.git/

PS> cd repo

PS> echo "hello" > README.md

PS> git add -A; git commit -m "initial"
[trunk (root-commit) b3d17c1] initial
 1 file changed, 1 insertion(+)
 create mode 100644 README.md

# Create 1000 branches, feat-0 through feat-999
PS> 0..999 | % { git branch "feat-$_" }

PS> jj init --git-repo=.
Done importing changes from the underlying Git repo.
Initialized repo in "."

PS> git pack-refs --all

PS> jj branch delete feat-0
Failed to export some branches:
  feat-0: Failed to delete: The packed-ref transaction could not be committed
```

## Expected Behavior

The branch feat-0 is removed from Git.

## Actual Behavior

The branch feat-0 is not removed, and the error is displayed:

> Failed to export some branches:
>   feat-0: Failed to delete: The packed-ref transaction could not be committed

## Specifications

- Platform: Windows 11 Version 22H2
- Version: jj 0.12.0-90e241cc9593e630c6a58e87559669896bf3926e

**Comment by yuja** [comment]
Thanks for debugging the issue. File deletion is a hard problem on Windows.

https://wiki.mercurial-scm.org/UnlinkingFilesOnWindows
https://repo.mercurial-scm.org/hg/file/a93e52f0b6ff/mercurial/win32.py#l725

This might be caused by gitoxide, but I haven't investigated it yet. (and I don't have Windows machine :)

We've migrated `git::import_refs()` to gitoxide at 044716ee, which means the packed-refs file is probably accessed by long-lived `gix::Repository` instance. Rust's stdlib appears to set `FILE_SHARE_DELETE` by default, but gix seems to be using mmap depending on the file size (> 32kiB), so the situation might be different.

https://github.com/Byron/gitoxide/blob/gix-v0.55.2/gix-ref/src/store/packed/buffer.rs#L33

FWIW, flaky Windows CI failure we've seen randomly might be a similar problem, but I don't know how tempfile and atomic renaming work on Windows.

**Comment by ilyagr** [comment]
> and I don't have Windows machine :)

You may already be well aware of it, but I'll mention the existence of https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/.

I've been trying my luck with it. It seems to work, but it turned out that I don't have a machine on which virtualization works well right now (it works, but ends up using painfully slow software emulation instead of CPU virtualization features). You might have better luck. In principle, it should also be possible to convert those images in a format QEMU supports using QEMU's conversion tool.

**Comment by yuja** [comment]
> it should also be possible to convert those images in a format QEMU supports

Perhaps. I just wanna be away from Windows as much as possible. ;)

**Comment by martinvonz** [comment]
I have a Windows computer. I'll try to find time to look into this tomorrow, or maybe on the weekend.

**Comment by yuja** [comment]
Can you test this on Windows? Hopefully it will reproduce the problem.
https://gist.github.com/yuja/b922bc0881c0912dad9c1a6a78f0703f

**Comment by jennings** [comment]
It looks like it reproduces it for me:

```
> .\target\debug\jjrepro.exe
[src\main.rs:46] repo_path.join(".git").join("packed-refs").metadata().unwrap().len() = 62103
[src\main.rs:52] &repo.refs = Store {
    git_dir: "test-repo\\.git",
    common_dir: None,
    object_hash: Sha1,
    write_reflog: Normal,
    namespace: None,
    packed: SharedFileSnapshotMut(
        RwLock {
            data: Some(
                FileSnapshot {
                    value: Buffer {
                        data: Mapped(
                            Mmap {
                                ptr: 0x0000020d99820000,
                                len: 62103,
                            },
                        ),
                        offset: 46,
                        path: "test-repo\\.git\\packed-refs",
                    },
                    modified: SystemTime {
                        intervals: 133470452149923632,
                    },
                },
            ),
        },
    ),
}
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FileTransactionCommit(PackedTransactionCommit(Commit(Error { error: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }, instance: File { inner: Handle { id: 1002, _marker: PhantomData<gix_tempfile::handle::Writable> }, lock_path: "test-repo\\.git\\packed-refs.lock" } })))', src\main.rs:53:26
```

**Comment by yuja** [comment]
Reported as https://github.com/Byron/gitoxide/issues/1183

Thanks for testing.
