### ISSUE TITLE
FR: Better handling of binary data in jj diff

### ISSUE THREAD

**Issue by dbarnett** [martinvonz/jj#2757]
**Is your feature request related to a problem? Please describe.**
When I add a binary file and view it in `jj diff`, it shows giant ugly adds/diffs of binary data. This bloats the diff output making it hard to navigate through changes to the other files.

**Describe the solution you'd like**
`jj diff` should by default just note that there was some add/change of binary data, not present a giant diff of the bytes. It could either use implicit detection or explicit metadata/config to decide which files to include as literal content in the diffs.

**Describe alternatives you've considered**
Alternatively diffs could still include the binary data but rely on viewer/pagers to just be more clever about how they _show_ the data, such as showing image data visually as images and making navigation easier to skip over huge mundane files of diffs.

**Additional context**
Screenshot of such an ugly diff:
![Screenshot of ugly diff of favicon.ico file](https://github.com/martinvonz/jj/assets/65244/b6852378-54aa-40e8-a81a-313fd6e47a1a)

Also worth noting: "binary" files are the most obvious part of this problem (and a case where `git diff` does better than `jj diff`), but I also have similar pain points with enormous _non-binary_ files like package-lock.json.

**Comment by martinvonz** [comment]
Agreed. This should be easy to fix for the binary case. I think Piper (and probably Perforce) use a heuristic of checking for null bytes (and maybe some other bytes?) in the first 1KiB or something like that. We should check what a few different tools do. It probably makes sense to copy Git's heuristic since that's what "everyone" uses.

Not sure what to do for the "large non-binary" case. Seems like we can leave that for later. Maybe it'll be something like `.gitattributes`.

**Comment by arxanas** [comment]
Regarding the large non-binary case, scm-record supports folding/unfolding files (and files start as folded). I usually [use it as a difftool in Git](https://github.com/arxanas/git-branchless/wiki/Command:-git-branchless-difftool) when I need to skip over big files. It looks like [`delta` supports jumping to the next and previous files](https://github.com/dandavison/delta#features), which I didn't know until just now. We could try to integrate with either of those if we wanted to get file jumping behavior for free.

**Comment by ilyagr** [comment]
> Regarding the large non-binary case, scm-record supports folding/unfolding files (and files start as folded). I usually [use it as a difftool in Git](https://github.com/arxanas/git-branchless/wiki/Command:-git-branchless-difftool) when I need to skip over big files.

Neat! I guess we could just disable the editing feature in the version of `scm-record` that comes with `jj`. I'm not sure what we'd call the tool, though, since it probably shouldn't be the default.

> It looks like [delta supports jumping to the next and previous files](https://github.com/dandavison/delta#features)...

The way `delta` supports this is pretty amusing. It gets `less` to have a pre-populated search term for symbols like `Δ` that `delta` use to mark files (I guess `less` has an option for this?). So, the commands for finding the next/previous match (n and N) find these symbols.

You can see the exact search term by pressing `/ <up>` in `less` after starting it with `delta`.

I'm not sure whether this can work for any pages other than `less`.

**Comment by arxanas** [comment]
> I'm not sure what we'd call the tool, though, since it probably shouldn't be the default.

I guess we could add an `--interactive` flag to `jj diff` 🤷. I guess the main differentiator between scm-record and the existing output is that it's not meaningful to pipe the output of scm-record elsewhere. But maybe it should indeed just be exposed via some kind of `--tool` argument; I guess after invoking the user-provided tool, jj is no longer responsible for ensuring that it produces pipeable output.

> The way delta supports this is pretty amusing. It gets less to have a pre-populated search term for symbols like Δ that delta use to delimit files (I guess less has an option for setting the search term on launch?). So, the commands for finding the next/previous match (n and N) find these symbols.

🤣

**Comment by dbarnett** [comment]
Exactly, I had been using delta and that skip to next file/chunk works okayish but seems to have some awkward corner cases.

Anyway definitely doesn't need to be perfect as long as jj's diffs can work at least as well as git's.

**Comment by jyn514** [comment]
> Agreed. This should be easy to fix for the binary case. I think Piper (and probably Perforce) use a heuristic of checking for null bytes (and maybe some other bytes?) in the first 1KiB or something like that. We should check what a few different tools do. It probably makes sense to copy Git's heuristic since that's what "everyone" uses.

looks like git's heuristic is "do the first 8000 bytes contain a null character": https://github.com//git/git/blob/eea0e59ffbed6e33d171ace5be13cde9faa41639/xdiff-interface.c#L193-L199

**Comment by jyn514** [comment]
i'm working on implementing this

**Comment by jyn514** [comment]
hmm. it is not too hard to avoid reading the full file contents if we just want to know if the file is binary using git's heuristic. but for `diff --stat`, if we want to match git, we would also show the the file size:
```
; git diff --no-index grey-ferris.png .gitignore --stat
grey-ferris.png => .gitignore | Bin 527705 -> 23 bytes
 1 file changed, 0 insertions(+), 0 deletions(-)
```
currently, that's tricky because `diff_content` only has access to a `Box<dyn Read>`, i.e. it cannot determine the length without reading the full file.

how do you feel about just reading the file contents unconditionally, without git's heuristic to try and avoid reads? that would simplify things, and make it easy to show `diff --stat`.
the other alternative i can think of is to add a `Seek` bound to `MaterializedTreeValue`, which works, but adds restrictions on all backends; or to just omit the file size for --stat.

**Comment by martinvonz** [comment]
> how do you feel about just reading the file contents unconditionally, without git's heuristic to try and avoid reads?

Sounds good to me, thanks.

That reminds me that there was some work on Git about two years to make it possible to read file sizes over the network without having to download the file. Maybe we'll want to update the backend trait to add support for that eventually.
