### ISSUE TITLE
Simplify conflicts per file when materializing them

### ISSUE THREAD

**Issue by martinvonz** [martinvonz/jj#2795]
If you have a 3-sides conflict where some files have conflicts between sides 1 and 2 while other files have conflicts between sides 2 and 3, we materialize those conflicts with unchanged sections in the conflict markers. I think it should work to instead simplify them before materializing. We should still be able to restore the conflict when we parse it (when snapshotting the working copy).

We should also make `jj status` show the number of conflicts per path after simplification.

**Comment by charypar** [comment]
Fwiw, this is the only complaint I have about `jj`. At least I think this issue is what I'm seeing. 

Everything else about jj works brilliantly, the only difficulty I've had with it (and I've only been using it in anger in a real-world workflow for a week or so), is when resolving conflicts. 

This might be down to the specific workflow - I'm in a repository with github Pull Request workflow, where merge policy is squash & merge, which I imagine makes a difference in identifiying merge base, and such, and automatically resolving conflicts.

From my limited experience, compared with `git`s conflict markers, `jj`s are quite often bigger (on at least some conflicts) and for me personally, harder to understand and disorienting (this may improve as I get used to them). I wish I had more specific feedback, but I can't really go beyond a few patterns I noticed:

* materialized conflict markers sometimes include code which was removed by one of the sides, but it is in the diff side of the markers as context (no + or -). The code it was replaced with by the same side was _outside_ of the markers on at least one occasion.
* resolving conflicts when rebasing a branch tends to lead to descendants of resolved commits having further, and more-sided conflicts. This may well be down to the specific resolutions I've chosen, as I'm not exactly sure what I'm trying to aim for in the conflict resolution. What I've tried so far is to end up with code which looks as if I've made the changes in the commit being rebased to the code it's being rebased onto. But because there's a commit which follows the one I'm rebasing, where I've made further changes to the original code in the parent, that leads to further conflicts, so I think that may not be the right strategy to attempt?

On at least one occasion I've resorted to avoding a rebase and instead doing a merge from the target branch (master in that case) into the branch I was trying to update first, and resolving the merge conflict with git - and even in that case, git's conflict markers were significantly tighter and easier to fix than `jj`s (when I created a new commit with both branches as parents).

I do appreciate this feedback is not super helpful, because I don't have specifics to share (this is all happening on a private repository), hopefully I can share some actual specific examples on public repos in the future.

I also want to say that I absolutely love everything else about jj, great, great work.
