### ISSUE TITLE
FR: exclude specific files from a diff

### ISSUE THREAD

**Issue by jyn514** [martinvonz/jj#2915]
**Is your feature request related to a problem? Please describe.**
I want to avoid viewing diffs for large generated text files, such as Cargo.lock. With git, I can use `git diff ':!Cargo.lock'` (see https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-exclude). AFAICT `jj diff` does not have an equivalent.

**Describe the solution you'd like**
I am not sure a good syntax for this. git's syntax is somewhat baroque, and very difficult to find in the docs. maybe `diff` could have a `--filter` command with a custom syntax, like `jj log --revisions` or `nextest --filter-expression`? or if that's too much design, `--exclude` would work fine, like `fd --exclude`. 

**Describe alternatives you've considered**
- shell pipelines, e.g. `fd | rg -v foo | xargs jj diff`. this *works* but is longer and easy to mess up; and it's hard to infer jj's defaults, especially WRT .gitignore.

**Additional context**

**Comment by arxanas** [comment]
Do we have a concept of "pathsets" yet 🙂? Conceivably we would want to use all the same patterns in a revset to specify commits that do/don't touch a certain kind of file.

**Comment by yuja** [comment]
> Do we have a concept of "pathsets" yet 🙂?

No, not yet. Perhaps, a primary expression will be similar to string patterns (e.g. `glob:*.rs`), but the underlying implementation will be different.

I think it's good to have a shorthand for common queries. `--ignore PAT` (or `--exclude PAT`) will be equivalent to `all() & ~PAT` for example.

**Comment by thoughtpolice** [comment]
> Do we have a concept of "pathsets" yet 🙂? Conceivably we would want to use all the same patterns in a revset to specify commits that do/don't touch a certain kind of file.

Mercurial calls these ["Filesets"](https://www.mercurial-scm.org/doc/hg.1.html#specifying-file-sets), as Martin noted to me in https://github.com/martinvonz/jj/issues/2286 while discussing another issue. I think they would be great to have and make a lot of functions that take path-like arguments much more expressive in some cases.

**Comment by PhilipMetzger** [comment]
Basically I'm onboard for both filesets or pathsets, whatever we call them in the end. The current question for is though how we want to call the flag for `jj diff`, `--ignore` or `--exclude`? I'm in favor of `ignore` at the moment, but this is not a strong opinion.

**Comment by martinvonz** [comment]
And I'm for `--exclude`. My problem with `--ignore` is that users might think it's related to `.gitignore`.

**Comment by joyously** [comment]
I'm with Martin for ``--exclude` being distinguished from the ignore file.
Also, it's short version could be `-x`? (whereas `--ignore` would be `-i` which means interactive)

**Comment by jyn514** [comment]
completely unrelated but @joyously i *love* your username omg

**Comment by jeremyelalouf** [comment]
Hi everyone, nobody treated this issue and is it still wanted ? I would love to do it :)

**Comment by martinvonz** [comment]
@jeremyelalouf: I haven't heard any other takers, so go for it. Thank you!

I think a good place to start looking is here:
https://github.com/martinvonz/jj/blob/3e72c439704df7698bd039159962949f1a065eab/cli/src/cli_util.rs#L1047-L1058

**Comment by jeremyelalouf** [comment]
Great thanks, I'll try to finish it as soon as possible :p

**Comment by yuja** [comment]
Some idea on pattern naming. It's inconsistent in Mercurial.

### Axes

* path normalization
  * cwd: cwd-relative filesystem path
  * root: workspace-relative path (or `RepoPath`)
  * unnormalized: raw string (such as glob matching file name `*.c` or regex)
* matching condition (or where to anchor)
  * prefix: path prefix (files under directory recursively, or exact file path)
  * file: exact file path
  * files-in: files in directory non-recursively
  * name: file name component (or suffix match)
  * substring: substring match
* string pattern syntax (+ case insensitive or not?)
  * literal: literal
  * glob: extended glob
  * regex: regular expression

NOTE: not all axes have to be multiplied. For example, prefix + glob won't be
that useful since it can be expressed as `glob:"<glob>/**"`.

### Pattern kinds that probably make sense

* literal patterns (default: cwd + prefix)
  * `"<path>"`, `cwd:"<path>"`: cwd + prefix + literal
  * `file:"<file>"`: cwd + file + literal
  * `files-in:"<dir>"`: cwd + files-in + literal
  * `root:"<path>"`: root + prefix + literal (= `path:` in hg)
  * `root-file:"<file>"`, `exact:"<file>"`: root + file + literal  (= `filepath:` in hg)
  * `root-files-in:"<dir>"`: root + files-in + literal
* glob patterns (default: cwd + file)
  * `glob:"<glob>"`, `cwd-glob:"<glob>"`: cwd + file + glob
  * `root-glob:"<glob>"`: root + file + glob
  * `name-glob:"<glob>"`: unnormalized + name + glob (=~ `relglob:` in hg)
* regex patterns
  * TODO: unnormalized + file + regex (= `re:` in hg)
  * TODO: unnormalized + substring + regex (= `relre:` in hg)

---

### Mercurial pattern kinds

```
    a pattern is one of:
    'glob:<glob>' - a glob relative to cwd
    're:<regexp>' - a regular expression
    'path:<path>' - a path relative to repository root, which is matched
                    recursively
    'filepath:<path>' - an exact path to a single file, relative to the
                        repository root
    'rootfilesin:<path>' - a path relative to repository root, which is
                    matched non-recursively (will not match subdirectories)
    'relglob:<glob>' - an unrooted glob (*.c matches C files in all dirs)
    'relpath:<path>' - a path relative to cwd
    'relre:<regexp>' - a regexp that needn't match the start of a name
    'set:<fileset>' - a fileset expression
    'include:<path>' - a file of patterns to read and include
    'subinclude:<path>' - a file of patterns to match against files under
                          the same directory
    'rootglob:<glob>'
```
https://repo.mercurial-scm.org/hg/file/6.6.3/mercurial/match.py#l180

**Comment by yuja** [comment]
30984dae4a92fbee0dc0b0cbcbaefab2a93a2aa3
