### ISSUE TITLE
Empty files in jj split

### ISSUE THREAD

**Issue by benbrittain** [martinvonz/jj#3016]
## Description
Empty files can not be split out of the current commit

## Steps to Reproduce the Problem

1. touch jj-is-the-best
2. `jj split`
3. `jj-is-the-best` is not selectable.

## Expected Behavior

Empty files should be able to be selected

## Actual Behavior

Empty files can not be selected

## Specifications
- Platform: Linux
- Version: `jj 0.14.0`

**Comment by martinvonz** [comment]
Perhaps actually a bug in [scm-record](https://github.com/arxanas/scm-record/)

**Comment by benbrittain** [comment]
This surfaces with both ```diff-editor = ["scm-diff-editor", "--dir-diff", "$left", "$right"]  ``` and the `:built-in` but I think the builtin is scm-diff-editor so, that might be the same thing :upside_down_face:

**Comment by martinvonz** [comment]
If you're curious, you can with e.g. Meld or vimdiff. I'd be a bit surprised if the bug is not in scm-record/scm-diff-editor. What jj does is to just dump the files to two directories (before+after) and then snapshots them just like a regular working copy (and we would have known if snapshotting of empty files wasn't working).

**Comment by arxanas** [comment]
Does the file appear in the UI and it simply isn't selectable, or it doesn't appear at all?

**Comment by benbrittain** [comment]
It appears but is not selectable

**Comment by arxanas** [comment]
Thanks, I filed https://github.com/arxanas/scm-record/issues/26 to track it. I don't think I'll be able to get to it anytime soon myself.

**Comment by arxanas** [comment]
Hmm, I'm actually not sure if it's a bug in scm-record or jj. I think my intention with `scm-record` was that all files should have at at least one section. New files should be marked with a file mode change (from the `0` mode), and possibly the scm-record+jj integration doesn't supply that to the UI. (My original understanding was simply that the empty file did not appear in the UI at all, which is similar to previous bugs.)

**Comment by peacememories** [comment]
I noticed the same behavior in `jj squash` and `jj split`. This is not just an inconvenience but leads to subtle errors, because the files show as non-selected, and are not selectable, but as far as I can tell the tool acts like they are selected. So a `split`, `squash` or `move` with empty files will *always* act on these files. This led to removals of marker files accidentally making their way into a branch they shouldn't have been in, in my case.
(This is especially fun when programming in python, because empty `__init__.py` are *everywhere* :sweat_smile: )

**Comment by Zoybean** [comment]
Just tested locally in version 0.15.1-bf76080f42f77cad934d9a5202c7b7d29ab2c890. Running `jj move -i` and:
- not selecting anything 
- selecting all but empty files

Leads to the expected behaviour: i.e. only the selected changes are moved. So at least with `jj move`, the only issue seems to be with the UI preventing selection.
