### ISSUE TITLE
FR: change `checkout` to an alias for `rebase -r @`

### ISSUE THREAD

**Issue by jyn514** [martinvonz/jj#3019]
**Is your feature request related to a problem? Please describe.**
i was showing jj to a friend the other day who mentioned that she really misses the way `git checkout branch` will bring the uncommitted changes with you to the other branch, it's a major part of her workflow.

**Describe the solution you'd like**
it makes sense that `jj new` doesn't do this, but since `jj checkout` is explicitly here only for familiarity with people familiar with `git checkout`, maybe it makes sense to make it more similar? we can still leave the deprecation notice if preferred.

`@` isn't *always* what would be the tip of a branch in git, so maybe it makes sense only to do this if `@` doesn't have a description and it has no child commits?

**Describe alternatives you've considered**
- leave checkout as-is
- suggest `jj rebase -r @` in `jj checkout`

**Additional context**

**Comment by PhilipMetzger** [comment]
> i was showing jj to a friend the other day who mentioned that she really misses the way `git checkout branch` will bring the uncommitted changes with you to the other branch, it's a major part of her workflow.

An adaption of the workflow is to have a local commit with all the uncommited changes, which you then reparent when switching work. This is all clearly explained in the FAQ. 

> it makes sense that `jj new` doesn't do this, but since `jj checkout` is explicitly here only for familiarity with people familiar with `git checkout`, maybe it makes sense to make it more similar? we can still leave the deprecation notice if preferred.
> 
> `@` isn't _always_ what would be the tip of a branch in git, so maybe it makes sense only to do this if `@` doesn't have a description and it has no child commits?

Now that we finally got around to deprecate `jj checkout`, I'd like it to keep it so.

**Comment by thoughtpolice** [comment]
We had hoped to remove `checkout` (and `merge`) entirely later on; they aren't shown up in the `help` anymore by default, so they're not particularly discoverable anymore either, I'm afraid. So if we changed their behavior to something new like this, I think we'd have to walk back on that a bit, and then it's not clear deprecating is a good strategy or not, since it's no longer just a specialization of `jj new`.

An alias like `aliases.foo = ["rebase", "-r", "@", "-d"]`, then you do `jj foo <revision>` would work just fine for this workflow, I think. I use little aliases like this all the time (`aliases.yeet = [ "move", "--from", "@", "--to" ]` for example).

Actually, it seems rather useful for some things, now that I've tried it. Of course, it's all in the name. I'm not sure we want to sanction another name for this; it might be best left as an alias, but for right now users can't override builtin commands anyway. So we'd have to go through the full removal cycle before you could reclaim the `checkout` command. `co` is the old alias for checkout and already used as well... I'm not sure what to call it.

**Comment by ilyagr** [comment]
I originally thought you'd want `-b`, not `-r`. If `checkout` didn't exist, you could have `aliases.checkout = ["rebase", "-d"]`  (`-b @` is the default). It's a neat use of the word. I like it in theory, but I think there's no need for it.

But if you really mean `-r`, I don't like as much. I often have several commits of "uncommited changes" (you could think of them as stashes + uncommited changes, I suppose), and just picking the top one seems bad. Actually, for me, the right option would be `-s` "the closest commit in `::@` that is a child of a branch", that is `-s 'roots(branches() .. @)'` I think.

**Comment by martinvonz** [comment]
I remember a friend of mine telling me a long time ago that `git checkout`'s behavior was confusing because it moved changes between branches. The `gitless` authors say the same thing [in their paper](https://core.ac.uk/download/pdf/78072747.pdf). So I suspect it's actually more intuitive to keep the current behavior, except to people who have gotten used to Git's behavior (which is of course a lot of people). It's easy to define an alias for `jj rebase -r @` for users who want that. I'd prefer to not define such an alias (or command) by default unless we hear this request very frequently. I hope it's transitional (I feel like I personally very rarely want to keep "uncommited" changes as I update between commits).

**Comment by Zambito1** [comment]
@martinvonz The only intuitive interface is the nipple. Everything else is learned. This is important because nothing about version control systems in general are really intuitive, so I don't think it's a valuable metric. The two metrics I think are more applicable are: usefulness and familiarity.

I personally think it is useful to separate the actions of selecting a new working commit in the graph, and moving changes from one commit in the graph to another. It seems like you agree, since `jj` exists :).

Since many people are familiar with the workflow that they use in `git` where they drag changes with them, I think it could be good in some capacity to provide this in `jj`. Maybe even just documenting a custom alias like what @thoughtpolice wrote somewhere, for people coming from `git` who want that behavior.

On a related note - aliases take priority over existing subcommands, right? Couldn't one actually define that `foo` alias as `checkout`, and it work as they want?

**Comment by thoughtpolice** [comment]
> On a related note - aliases take priority over existing subcommands, right? Couldn't one actually define that `foo` alias as `checkout`, and it work as they want?

No, that specifically isn't supported right now, I checked when I deprecated `checkout`, and at least to me it's not clear if we want that in general since, among other things, I *think* we can have aliases refer to each other (so then you have to handle cycles from expanding aliases).

**Comment by Zambito1** [comment]
Overriding default behavior with an alias definitely seems like something one would want to do. It's similar to adding default flags to a command, ie: `alias ls='ls --color=always'`.

One interesting solution for the cycle depth issue: an alias could go "out of scope" when it is use. There would have to be a clear error that this is what is happening rather than just saying the alias is undefined (it would seem to be defined to the user), but I think this would be a reasonable solution to that problem.

**Comment by PhilipMetzger** [comment]
> @martinvonz The only intuitive interface is the nipple. Everything else is learned. This is important because nothing about version control systems in general are really intuitive, so I don't think it's a valuable metric. The two metrics I think are more applicable are: usefulness and familiarity.
> 
> I personally think it is useful to separate the actions of selecting a new working commit in the graph, and moving changes from one commit in the graph to another. It seems like you agree, since `jj` exists :).
> 
> Since many people are familiar with the workflow that they use in `git` where they drag changes with them, I think it could be good in some capacity to provide this in `jj`. Maybe even just documenting a custom alias like what @thoughtpolice wrote somewhere, for people coming from `git` who want that behavior.

I'm weary of doing things in the Git way, as `jj` is _Git compatible_ but not _Git_. If you can't get over the hump of learning a new tool and adjusting your workflows, why bother? 

IMO, the actionable thing is to document an alias in the FAQ and then be done with it.

> I'd prefer to not define such an alias (or command) by default unless we hear this request very frequently.

Agreed, people should adjust to `jj` not the other way around, `jj` adjusting to _Git_ workflows.

**Comment by jyn514** [comment]
> Agreed, people should adjust to `jj` not the other way around, `jj` adjusting to _Git_ workflows.

:+1:

**Comment by epage** [comment]
> Overriding default behavior with an alias definitely seems like something one would want to do. It's similar to adding default flags to a command, ie: alias ls='ls --color=always'.

While I find this a nice way of specifying settings, the main risk is with the user or automation needing to access the original version of the command.

**Comment by epage** [comment]
While I've not run into this yet, so I don't know how the output is, could this be something where we want to help the user know what is going on and what their options are?  So we're not directly solving it but helping the user solve it.

**Comment by PhilipMetzger** [comment]
> While I've not run into this yet, so I don't know how the output is, could this be something where we want to help the user know what is going on and what their options are? So we're not directly solving it but helping the user solve it.

I don't think there's anything we should do yet, but feel free to mention it in the FAQ. 

From my previous reply: 

> IMO, the actionable thing is to document an alias in the FAQ and then be done with it.
