### ISSUE TITLE
FR: Style immutable nodes differently in log

### ISSUE THREAD

**Issue by martinvonz** [martinvonz/jj#3111]
**Is your feature request related to a problem? Please describe.**

`jj log` doesn't indicate which commits are immutable.

**Describe the solution you'd like**

We should indicate in some way which commits are immutable. Maybe we would use a `◆` symbol for it.

**Describe alternatives you've considered**

Mercurial (at least with the setup we use at Google) does it by coloring the commit id differently. We could do that in addition or instead.

**Comment by necauqua** [comment]
A slightly related thing that could be done here as well is configurable node symbols.

So there will be a generic config, something similar to `node.default = '◉'`, `node.immutable = '◆'`, maybe also `node.working-copy = '@'` although we had a bunch of discussions about how wc being @ is important because the revset symbol for wc is @

Slightly less related thing is having said config for any number of arbitrary revsets, not just immutable, I think that was also mentioned by someone.

I don't know if there were any feature requests for any of above

**Comment by zummenix** [comment]
@martinvonz Perhaps, current issue could be closed, since there is #3260?
