### ISSUE TITLE
Add support for `jj diff` to emit unified diffs

### ISSUE THREAD

**Issue by durin42** [martinvonz/jj#33]
The diff format produced by `jj diff` is supposed to be more human readable, but it makes it harder to collaborate with copy/pasted patch files etc when that becomes an efficient way to share with others. It's also slower to digest for me, as I've got 20 years invested in reading unidiffs natively and colors aren't a great visual cue for me.

(I'd kind of like to do this work, but figured I should track it in a bug anyway.)

**Comment by martinvonz** [comment]
I agree.

I'm not very happy with the default format in general (it works very well in some cases, but pretty poorly in others). I think I want line-level diffs with word-level differences highlighted (like Mercurial does by default). I want it to target humans by default, which (to me) means no `a/` prefixes on paths, and now hard-to-read `+++` and `---` lines.

Regardless of that, I'm all for an option for machine-readable unified diffs.

> (I'd kind of like to do this work, but figured I should track it in a bug anyway.)

Great! You should be able to call `Diff:: for_tokenizer(vec![before, after], &find_line_ranges)` to get an iterator over `DiffHunk`. If one side of the inputs is a conflict, the command should probably error out.

**Comment by martinvonz** [comment]
@durin42, with the commits I just pushed, you can use `jj diff --git` to get Git's kind of unified diffs.

Note that color codes cannot be turned off yet, so if you need color-code-less diffs, you'll need to copy+paste from the terminal or something like that. It's easy to turn off colors depending on whether the output is a TTY but I haven't done it yet because I often do e.g. `jj log | less`. I'd like to add pager support and/or `--color=never` or similar. The latter is not quite as simple as it sounds because the `Ui` object is currently created before parsing arguments.

I hope you don't mind that I did the work.
