### ISSUE TITLE
FR: A revset to determine private commits that may not be pushed

### ISSUE THREAD

**Issue by jennings** [martinvonz/jj#3376]
**Is your feature request related to a problem? Please describe.**
In chat, people have asked for a way to define commits that Jujutsu refuses to push (examples: [one](https://discord.com/channels/968932220549103686/969291218347524238/1220413138814505031), [two](https://discord.com/channels/968932220549103686/968932220549103689/1222208640317001757)). Currently, the only restriction is that commits with an empty description may not be pushed.

**Describe the solution you'd like**
Define a new revset alias named `private_roots()` that describes revisions (and their descendents) that may not be pushed to remotes. By default, this will be defined as:

```toml
revset-aliases.'private_roots()' = 'description(exact:"")'
```

The name is open for bikeshedding, some options:

- `private_roots()`
- `private_changes()`

When pushing changes, Jujutsu should determine if any changes being pushed match this revset. If so, then the push is aborted.

Suppose my convention is to write "wip:" at the beginning of my private changes. Then, I would define this revset alias to avoid pushing them by mistake:

```toml
revset-aliases.'private_roots()' = 'description(exact:"") | description(glob:"wip:*")'
```

**Alternative solutions**
Another option would be to explicitly mark changes as private. For example, running `jj private set -r REV` would mark the specified changes as private, and they could not be pushed until unmarked with `jj private clear -r REV`

**Comment by yuja** [comment]
It might have to be per-remote configuration. The user might want to push wip commits to their fork, but not to the upstream repo. I think @ilyagr suggested that somewhere.

**Comment by noahmayr** [comment]
> It might have to be per-remote configuration. The user might want to push wip commits to their fork, but not to the upstream repo. I think @ilyagr suggested that somewhere.


If `if()` expressions and some equality check were supported in revsets (not sure if that's a good idea though), the following would work:
```
revset-aliases.'private_changes(remote)' = 'if(equals(remote, "origin"), description(exact:"") | description(glob:"wip:*"))'
```

**Comment by yuja** [comment]
Revset doesn't have a runtime string variable, so `equals()` will have to be substituted to `equals("foo", "bar")` by alias. That works, but looks a bit weird.

Another cryptic idea:
the constraint could be expressed as a revset expression at a future remote?
Something like: "Suppose the commits had been pushed to the remote, which commits should have been refused to push"
```toml
# When pushing the local "main" branch to the remote "upstream", the future
# "main@upstream" ancestors shouldn't include commits whose descriptions are "wip".
# If the remote is "my_fork", "*@upstream" branches don't exist?
'private_changes()' = '::present(main@upstream) & description(glob:"wip")'
```

**Comment by hooper** [comment]
Just to be clear, will there be any distinction between descendants of the private revset that are or aren't in the revset? Should we have `private_roots()` in the same way we have `immutable_heads()`?

Should we be worried about users being confused about that? I've had to explain "you can't have secret commits between draft commits" to new Mercurial users pretty frequently. The `jj private` approach might be less flexible than a revset, in a good way, if it uses something like Mercurial's phase roots. The commands could print messages like "foo and its 123 descendants are now private". This choice has implications for the efficiency of computing privateness, too.

If we _need_ the flexibility of revsets, it would be good to record the rationale here. Maybe just because it's less effort for the average user, since some users will be using something like "wip:" anyway?

Revset based privateness could change as a result of operations like rebase, split, or squash. Sometimes in desirable ways. Can we ensure a desirable result in all cases?

Regardless of the underlying approach, should we give users an easy way to get "private by default"? Would that be `jj new --private` or something else?  I don't think there's a good way for `jj new --private` to work with a purely revset based approach, although the "wip:" example could just use a commit message template instead.

What will we do if a user tries to merge a private commit and a non-private commit? Warn that the result is private?

**Comment by yuja** [comment]
> > Should we have `private_roots()` in the same way we have `immutable_heads()`?
> 
> I like this idea of calling it `private_roots()` instead of `private_changes()`. It gives _some_ indication that the privacy extends to descendents.

While `immutable_heads()` can be an optimization, having roots set wouldn't. I agree about consistency and clarity, though.

I personally don't think we'll need a strict set of "private roots" descendants that the Mercurial's phase-like model will provide. I like the idea of using revsets mainly because it's simpler than introducing phase roots, not because it's flexible.
