### ISSUE TITLE
FR: Format timestamps based on how long ago they were

### ISSUE THREAD

**Issue by willhbr** [martinvonz/jj#3782]
**Is your feature request related to a problem? Please describe.**

I would like to be able to format recent timestamps as a relative time (like `2 hours ago`) but would like older timestamps to be exact. I don't find a timestamp like `8 years ago` to be very useful, but I find it clearer to have recent timestamps be relative.

**Describe the solution you'd like**

I can see a few ways to implement this, and it'll depend on the shape of the template language. What I'd do is add a `.days_ago()` and `.hours_ago()` method to the integer type, and a `.is_older_than(timestamp)` method to the timestamp type. You could then do:

```tool
[template-aliases]
'format_timestamp(ts)' = '''
if(ts.is_older_than(3.hours_ago()),
  ts.format("%b, %d %Y at %H:%M"),
  ts.ago()
)
'''
```

This is of course stolen from the Ruby way of working with times.

**Describe alternatives you've considered**

A minimally invasive change would be to add a `.is_older_than_days(days)` method to timestamp, but that seems messy. Or don't put the `.days_ago()` method on integer and instead make it a free function. Or add a function that parses duration specifiers like `7d` and then a method that turns those into timestamps relative to now, and a way to compare two timestamps. Like: `ts.is_before(duration("7d").ago())`.

**Additional context**

This could be possible today and I just haven't realised it, it didn't look like it from the docs.

I've [got a working implementation](https://github.com/martinvonz/jj/commit/b359ed1a779f053c007ef38302435bfc5e5431d6). I'm happy to add some tests and documentation and open a PR.

**Comment by yuja** [comment]
Perhaps, the easiest implementation would be `timestamp.older_than(string)` or something that parses string argument as time or duration. (We use that for `commit.contained_in(revset)` because we don't have a revset type in template language yet.)

A better, more generic way is to add comparison operators and timestamp/duration constructor function: `committer.timestamp() < date(..)`. FWIW, I feel it's odd that integer type has duration constructors. It's weirder if it returned a timestamp. (Why integer knows the current time?)

For now, maybe you can abuse `.ago()` and `.contains("month")`, etc.

Related: https://github.com/martinvonz/jj/issues/3287

**Comment by ppwwyyxx** [comment]
`git-branchless`, `sapling`, `graphite` all by-default shows "how long ago" commits are in logs. 

IMO this is a better default than " 2024-07-22 16:15:53"
