### ISSUE TITLE
FR: automatically update op log via a file watcher

### ISSUE THREAD

**Issue by fowles** [martinvonz/jj#3855]
Assuming I understand things correctly, `jj` is a bit like `piper/citc` in that it keeps track of most states the workspace has been through via its [`op log`](https://martinvonz.github.io/jj/latest/operation-log/).

`citc` tracks every single save to the filesystem, whereas `jj` will capture a new entry in the op log whenever a `jj` command is run.  This means that if there are multiple saves that do not involve a `jj` command, then the op log will not see the steps along the way.

I would like to have some kind of filesystem watcher that triggers entries into the op log for every save.

I am happy to try and write PRs for this assuming you are amenable to the feature.

**Comment by ilyagr** [comment]
There has been some discussion of this, and I think there's a general agreement that we want some form of a "jj daemon".

One thing to be aware is is the Linux-only (FUSE) prototype at https://github.com/benbrittain/cultivate by @benbrittain .

Another thing to be aware of is that `jj` can already use `watchman` as a file watcher (but `jj` currently only queries it when a `jj` command is run): https://martinvonz.github.io/jj/v0.18.0/config/#filesystem-monitor

**Comment by ilyagr** [comment]
One problem with `watchman` is that it can be difficult to install. So, there have also been discussion of having support for some file watcher that can be linked into the `jj` binary.

**Comment by arxanas** [comment]
> Another thing to be aware of is that jj can already use watchman as a file watcher (but jj currently only queries it when a jj command is run): https://martinvonz.github.io/jj/v0.18.0/config/#filesystem-monitor

Watchman itself has a system to essentially register callbacks on file change events, without needing to daemonize your entire program: https://facebook.github.io/watchman/docs/cmd/trigger

You can configure this for yourself with an interactive Watchman command (I guess just have the trigger invoke any jj command that produces a snapshot): https://facebook.github.io/watchman/docs/cmd/trigger#simple-syntax

It would also be conceptually straightforward for jj to register such a trigger when querying Watchman. 

- I'm happy to provide more information or review a PR for this.
- The trigger can carry a bunch of useful information about specifically which files have changed since the last invocation, but the easiest implementation for jj would be to just ignore it and query Watchman directly in the same way that it already does.
- It looks like the `watchman_client` crate doesn't directly expose triggers; you could add it upstream,  or shell out to Watchman.
  - If shelling out, it should be straightforward to serialize/deserialize the Watchman JSON payloads with `serde_json`, but might take some onboarding time if you haven't used `serde` before.
- The documentation suggests that if you overwrite an existing trigger, it will reevaluate the trigger query, which we would want to avoid if the trigger is unchanged. So the implementation would probably need to call `trigger-list` before `trigger`.
- Not every user would want eager snapshots, so probably best to guard this behind a configuration option.

**Comment by fowles** [comment]
That is great information!  Let me poke at this stuff for a few days and see what I can do with it.  :)

**Comment by fowles** [comment]
https://github.com/facebook/watchman/pull/1221 adds API to the client for trigger.  Just waiting on their cla bot to process my cla.

**Comment by fowles** [comment]
https://github.com/martinvonz/jj/pull/3862 works on my local system.  I could definitely use suggestions on

1) how to test this (other than manually)
2) improvements to the code itself
