### ISSUE TITLE
FR: Add argument alias for `jj log --limit` matching `git log`

### ISSUE THREAD

**Issue by KiitoX** [martinvonz/jj#3868]
**Is your feature request related to a problem? Please describe.**
I'm used to using `git log`, where `-n <N>` or `-<N>` can be used to limit the number of commits shown. Having to remember to use `-l` instead, is a small but inconvenient hurdle.

**Describe the solution you'd like**
I've seen that `-n` is not otherwise used yet in `jj log`, and I would like the `git` options to be added as an alternative.

Ideally I would also like to be able to use the `-<N>` variant, though subjectively I feel that is less well known albeit very convenient. I am currently looking into whether that can be done with `clap` neatly...

**Describe alternatives you've considered**
I realize that technically `git log -n` is applied before reordering and formatting, but for me that behaviour has not been important. Adding the arguments `-n` and `--max-count` as aliases to `--limit` should be simple, but I'd understand if that break in behaviour might not be desired.

**Comment by martinvonz** [comment]
That should be trivial to implement (except for maybe the `-<N>` variant) but I'm not convinced it's worth it. It means we're spending two short names (`-l` and `-n`), making it harder to find a good short name for some future flag. I copied `-l` from `hg log`. I don't think I had realized that `git log` used `-n` instead. That seems like a good name since it matches the `head` command. If (and only if!) we have two names that we feel a similarly good, we should use the one from Git IMO, since that's what ~100x as many users are familiar with. So, I would personally be for a patch that deprecated `-l/--limit` in favor of a new `-n/--max-count` (or is there a better name than `--max-count`?).

**Comment by joyously** [comment]
`-n` could be short for `--number` or `--number-to-show` or `--needed` or `--no-paging` or `--not-all`.
I like `--limit`, but then I don't use Git much.

**Comment by KiitoX** [comment]
Yeah I don't love `--max-count` but also wouldn't know a better alternative other than `--limit` I guess

If I read the docs right `-<N>` could be possible as an optional positional(?) argument with a [RangedI64ValueParser](https://docs.rs/clap/latest/clap/builder/struct.RangedI64ValueParser.html#) on the range `-i64.MAX..-1` and with [allow_negative_numbers](https://docs.rs/clap/latest/clap/struct.Arg.html#method.allow_negative_numbers) set, but I'm unsure if that is worth the trouble

**Comment by yuja** [comment]
I personally don't mind if the short for `--limit` was `-n`.

`-<N>` could potentially have a different meaning in this context (e.g. `-0` to null-terminate entries), so I wouldn't add it unless there's a strong need.
