### ISSUE TITLE
Built-in diff editor doesn't redraw screen correctly in the presence of tabs

### ISSUE THREAD

**Issue by fschoenm** [martinvonz/jj#4001]
## Description

In some files (not sure which), there's a very annoying display bug in the `jj split` UI. Unfolding and folding a section doesn't clear parts of the text, which makes the whole UI kind of unusable in most cases.

Probably best seen in the video below.

## Steps to Reproduce the Problem

1. Have changes in your working tree.
1. `jj split`
1. Unfold and fold a larger file.

## Actual Behavior
 

https://github.com/martinvonz/jj/assets/687230/88ca8a7e-75a0-4f6c-9a3c-ab253396a12c

## Specifications

- Platform: Ubuntu 24.04
- Version: 0.18.0

**Comment by arxanas** [comment]
Hi @fschoenm, does the file in question have hard tabs (`\t`), or does it use spaces for indentation?

From the output, it looks like tabs to me. (Thanks for including the recording. An idle thought: perhaps we should also encourage users in the bug report template to include a recording or Asciinema screencast when demonstrating certain UI issues.)

If tabs, it may be the same problem as https://github.com/arxanas/scm-record/issues/2, recently fixed by @firestack in https://github.com/arxanas/scm-record/pull/37.

If it's the same, then we might want to push a new release for scm-record and pick it up in jj, since others have run into the same issue as well, like https://github.com/martinvonz/jj/issues/3944.

**Comment by fschoenm** [comment]
@arxanas I'm pretty sure it's tabs but I can check it tomorrow.

Thanks for the reference to the other ticket; I tried to find similar issues but didn't know what exactly to search for.

**Comment by arxanas** [comment]
> Thanks for the reference to the other ticket; I tried to find similar issues but didn't know what exactly to search for.

It's no trouble. I probably should have also reopened the other issue, since the underlying bug has not yet been fixed and merged into jj.

**Comment by firestack** [comment]
Just confirming here, I was having some issues with `jj resolve` in a repo so I built JJ with the latest from `scm-record` and it worked for tabs 👍🏻 

<img width="864" alt="image" src="https://github.com/martinvonz/jj/assets/6913198/c295f596-41df-46d0-be64-17b06c642237">

**Comment by msuozzo** [comment]
What's the status here? Does this just need a version bump and release?

**Comment by martinvonz** [comment]
Sounds like it to me. scm-record 0.4.0 was released yesterday. Can you try upgrading jj to that and send a PR, @msuozzo? Or we can just wait a day and hope that Dependabot will send a PR.

**Comment by firestack** [comment]
https://github.com/martinvonz/jj/pull/4639
