### ISSUE TITLE
FR: git fetch should fetch --all-remotes by default?

### ISSUE THREAD

**Issue by stacyharper** [martinvonz/jj#4434]
Given that multiple remote fetching is doable only when the users set up manually a config value with `jj config set --repo git.fetch '["origin", "upstream"]'`, and then they can use `jj git fetch --all-remotes`.

Why not making `--all-remote` the default? And leaving --remote <remote>` optional?

**Comment by essiene** [comment]
I think there are some subtle differences:

`--all-remotes` fetches from all the remotes known to the backing git repo. It doesn't directly use the configured remotes in `git.fetch`. Which means that the git repo can have many more remotes defined than what is listed in `git.fetch`.

That said, the behaviour for `jj git fetch` today is that if both `--all-remotes` and `--remote` are not specified, it will automatically fall back to using:
   - `git.fetch`
   - first remote found in backing git repo
   - the remote called `origin`

I think this meets the underlying intent of what you're suggesting, except for the fact that it falls back to `git.fetch` instead of the "all known remotes".

**Comment by stacyharper** [comment]
Ah okay! So it currently does what I expect. I thought `--all-remotes` was for all remotes from `git.fetch`

**Comment by essiene** [comment]
Thanks for confirming. Closing this as Won't Fix because WAI. Do re-open if needed.

Thanks.

**Comment by stacyharper** [comment]
It is possible to `config --user` so that all `git fetch` use `--all-remote` by default (or always)?
