### ISSUE TITLE
`jj log` after `git tag -d TAG` causes an unexpected rebase on git-co-located-repository

### ISSUE THREAD

**Issue by hymkor** [martinvonz/jj#4838]
## Description

On git-co-located-repository, `jj log` after `git tag -d TAG` causes an unexpected rebase.

### 1. Creating a git-colocated repository

```
$ git init
$ jj git init --colocate
$ echo step1 > step1
$ jj commit -m "step1"
$ git tag v0.1.0
$ echo step2 > step2
$ jj commit -m "step2"
```

### 2. Add a tag with `git tag`

```
$ git tag v0.2.0
$ jj log
```

### 3 . Delete the tag with `git tag -d` and `jj log`

```
$ git tag -d v0.2.0
$ jj log
Abandoned 1 commits that are no longer reachable.
Rebased 1 descendant commits off of commits rewritten from git
Working copy now at: ukrntnxz 24825366 (empty) (no description set)
Parent commit      : tsvpynmx 2fa59203 step1
Added 0 files, modified 0 files, removed 1 files
Done importing changes from the underlying Git repo.
@  ukrntnxz iyahaya@nifty.com 2024-11-12 04:52:20 24825366
│  (empty) (no description set)
◆  tsvpynmx iyahaya@nifty.com 2024-11-12 04:47:25 v0.1.0 git_head() 2fa59203
│  step1
◆  zzzzzzzz root() 00000000
```

Not only a tag, but also a commit seems to be abandoned.

## Expected Behavior

The last `jj log` does not rebase.

## Actual Behavior

![abandon-after-git-tag-d](https://github.com/user-attachments/assets/6eb3ed19-01cf-456f-9fdf-9402c1ea072e)

Lost files are recovered with `jj op undo`, but `rebase` is executed again at the next `jj log`.

## Specifications

- Platform: Windows 11
- Version: jj 0.23.0-5de285f5eb727b613434979cd9d83c30cabaffae

**Comment by bnjmnt4n** [comment]
This is working as intended as per https://martinvonz.github.io/jj/prerelease/config/#abandon-commits-that-became-unreachable-in-git. Deleting branches or tags via Git would abandon those commits if they became unreachable, and cause descendants to be rebased on top of the deleted commits' parents.

I believe this behaviour might be slightly more unintuitive because tagged commits are typically already ancestors of `trunk()` and are already immutable.

**Comment by hymkor** [comment]
Thank you for telling the reason.
I understand that this is the specification
