### ISSUE TITLE
test_git_colocated and test_git_colocated_rebase_on_import test failures

### ISSUE THREAD

**Issue by jonathantanmy** [martinvonz/jj#500]
When running `cargo test`, 2 tests fail. The screenshot shows the diff for one of them: notice that it's "main" instead of "master", and there is an extra space after one of the hashes.

![Screenshot 2022-08-29 14 41 19](https://user-images.githubusercontent.com/29559283/187306842-a2f2e1fe-a13e-494b-a00b-17cf988ecfdb.png)

I'll take a look at fixing them myself, but help is appreciated, of course.

## Specifications

- Platform: Linux
- Version: c83e563879 ("readme: make link to Discard a button", 2022-08-28)

**Comment by martinvonz** [comment]
I have `init.defaultbranch=main` in my system config (same as you presumably, since we have the same employer), but I also had `init.defaultbranch=master` in my `~/.gitconfig` (probably from some earlier testing trying to make tests hermetic). If I remove that, I see the same failure. So we need to make libgit2 not look at user/global configs and system configs when running tests.
