### ISSUE TITLE
NO_COLOR is not correctly overridden by ui.color config

### ISSUE THREAD

**Issue by neutralinsomniac** [martinvonz/jj#5041]
According to the docs, having NO_COLOR set in the environment, but having `ui.color` set to something like `always` should cause the NO_COLOR environment variable to get overridden, but it doesn't appear to work.

## Steps to Reproduce the Problem

1. `export NO_COLOR=1`
1. `jj diff` shows no color as expected
1. add `color="always"` to `[ui]` section of `~/.config/jj/config.toml`
1. `jj diff` still shows no color. interestingly, if `ui.diff.format` is set to `git`, the output shows some **bold** characters, but still no color. Perhaps this is a hint to where the issue lies.

- Platform: Tested on Mac + Linux
- Version: 0.24.0

**Comment by martinvonz** [comment]
I think the behavior is intentional, see commit 3d41db16. So this is probably just a documentation bug.

**Comment by martinvonz** [comment]
Oh, I'm sorry, I think I got it backwards. Maybe it's a regression that happened after the commit I linked to then.

**Comment by martinvonz** [comment]
The test case from that commit still exists and passes. Turns out `NO_COLOR= jj` (as the test case does) results in color, but `NO_COLOR=1 jj`(or `=0` or anything else) results in no color. However, `jj config get ui.color` behaves as it should:
```
$ NO_COLOR= jj config get ui.color
always
$ NO_COLOR=1 jj config get ui.color
always
```
So we seem to be setting the in-memory config correctly. I really don't know why `NO_COLOR=` and `NO_COLOR=1` would behave differently if the resulting config is the same. I've instrumented the code and checked that the return value from `color_setting()` is the same between the two cases too (that function gets called 3 times). So I still don't know what the problem is.

**Comment by martinvonz** [comment]
Now I've verified that we're actually even using the color formatter. Oh!! I bet this is `crossterm` messing with us! Yep, they do respect `NO_COLOR` since July 2023 (https://github.com/crossterm-rs/crossterm/pull/782). But since they're a library, they can't know whether there are "User-level configuration files and per-instance command-line arguments" that should override the `NO_COLOR` behavior. I'll see if we can at least tell `crossterm` to disable their checks.

BTW, I saw that the spec says that we `NO_COLOR` should not take effect if its value is an empty string, so we should also fix that (`NO_COLOR= jj` currently does disable color).
