### ISSUE TITLE
Crash when rebasing with confusing merges

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#635]
I managed to get `jj` to crash with a `jj duplicate` of a merge commit followed by `jj rebase`. After the `jj duplicate`, I get 
[this repository state](https://github.com/martinvonz/jj/files/9793272/lf_repo3.tgz). From there, I see the following behavior:

```
$ RUST_BACKTRACE=1 jj rebase -b list-keys -d master
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other("Git commit '6531d7715d1949d50d793b8456ed3cb994bc2f2c' already exists with different associated non-Git meta-data")', lib/src/store.rs:87:60
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   3: jujutsu_lib::store::Store::write_commit
   4: jujutsu_lib::commit_builder::CommitBuilder::write_to_repo
   5: jujutsu_lib::rewrite::rebase_commit
   6: jujutsu_lib::rewrite::DescendantRebaser::rebase_next
   7: jujutsu_lib::rewrite::DescendantRebaser::rebase_all
   8: jujutsu_lib::repo::MutableRepo::rebase_descendants
   9: jujutsu::commands::run_command
  10: jj::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

This uses today's `jj` main branch (commit 9da89) on Debian 11.

**Comment by martinvonz** [comment]
This is a variety of #27. It's interesting because it doesn't help to simply retry (unlike most cases). The problem is that the `jj duplicate` command gives you a second commit with all the same Git metadata, except for the commit timestamp. Then, when you rebase both duplicates, the will most likely get the same timestamp and thus exactly the same Git metadata, which causes the crash.

In case you need a workaround: modify e.g. the duplicate's description before rebasing it.
