### ISSUE TITLE
Unexpected divergent commits

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#666]
I came upon an example of unexpected divergent commits as discussed in https://github.com/martinvonz/jj/pull/636#issuecomment-1281119817 when interacting with git (repository inited with `--git-dir .`).

Start in [this repository state](https://user.fm/files/v2-a0da91322d448eb289dd6682e495a1f0/hwatch-repo.tgz). At that point, running `jj rebase -s b5375 -d clippy` creates several divergent commits, the ones with titles "Backspace to hide history" (change 57c3), "Disable header/ui" (change efb5), and everything in between. For a few of them, that can be explained by the `ig1` tag, but not for the last one.

After some `git push --force`, I got to [this repo state](https://user.fm/files/v2-94d8d34e59a1fc1ab43021541ad6c3b3/hwatch-repo--afterpushes.tgz), which still contains divergent commits. For instance, on my machine, the change `57c3` has two unabandoned commits, b5375 and fcb6. I'm mentioning this since sometimes `git push` resolves divergent commits.

**Comment by martinvonz** [comment]
I think this is another incarnation of #463. I took the first of your repo states, removed `.jj/repo/git_export_operation_id`, ran `jj describe -m foo` to make sure it was recreated. The rebase command you provided then created divergent commits. I then tried the same steps with the fix for #463 (PR #701) and there were no divergent commits. There's been a lot of different bugs caused by that. It will be nice to finally have that fixed.

**Comment by ilyagr** [comment]
That's great news, thank you! 

I agree this could either remove or decrease the frequency of the other problems that we were discussing, as well. Lately, most of my issues were caused (sometimes indirectly) by my attempts to deal with this sort of divergence.
