### ISSUE TITLE
Allow conflicts to be materialized in Git style

### ISSUE THREAD

**Issue by chooglen** [martinvonz/jj#823]
## Description

This improves interop with tools that only understand Git-style conflict markers, e.g. IDEs, `npm`.

We would probably make a config option for this, but it might also be nice to have a command that explicitly re-materializes the conflicted file (e.g. a user who prefers jj-style conflict markers and occasionally needs Git-style conflict markers for tooling).

**Comment by martinvonz** [comment]
Some things to keep in mind when implementing this (would probably become obvious for anyone who tries):

* If we want to preserve conflicts in the working copy, we need to be able to also parse the conflicts
* For conflicts with more than 1 remove and 2 adds, we'll presumably fall back to our usual marker style

**Comment by martinvonz** [comment]
Btw, in addition to this `git` style, we could also have a `snapshot` style that would look like this:

```
<<<<<<<
+++++++
A
-------
B
+++++++
C
-------
D
+++++++
E
>>>>>>>
```

That would correspond to our usual style (let's call it `diff`) that looks like this:
```
<<<<<<<
+++++++
A
%%%%%%%
-B
+C
%%%%%%%
-D
+E
>>>>>>>
```

**Comment by ilyagr** [comment]
Instead of solving the problem of supporting different conflict formats in the working copy, a possible simple compromise would be to have a `jj file edit` command that allows you to edit a file in an arbitrary revision in a temporary dir. It could more easily have a `--conflict-format` argument. This would still require implementing parsing the other conflict format, but it wouldn't require the command to figure out which conflict format is being used, and we wouldn't have to store that in the working copy.

Another possible name for this, suggested by @martinvonz a long time ago, would be `jj resolve --edit`, but while the command is mostly useful for conflicted files, it could also be useful for viewing an arbitrary file in another revision.

One possible set of names for conflict formats are `jj`, `diff3`, and `diff3+` for diff3 format extended to conflicts with more sides. The last two could also have aliases `git` and `git+`. (Strictly speaking, git supports [several conflict formats](https://git-scm.com/docs/git-merge#_how_conflicts_are_presented), but IMO the diff3 format is the only reasonable one. The zdiff3 format is [particularly confusing](https://lore.kernel.org/git/CAO_smVg=1gFBudrd70V2_AXSPOUTFz=j7QqBpbkvR7P_KqnBtQ@mail.gmail.com/T/#t), though some of the confusion in that discussion was my own misunderstanding).

**Comment by ilyagr** [comment]
Separately, there was a [discussion of this on Discord](https://discord.com/channels/968932220549103686/1270126919634911335). It's not mandatory reading (especially if you don't have an account), but I'd like to keep a link to it.

**Comment by sheremetyev** [comment]
Just for reference, here is parsing of conflict markers in VSCode: https://github.com/microsoft/vscode/blob/main/extensions/merge-conflict/src/mergeConflictParser.ts

Note that it supports multiple blocks separated by `|||||||`, which could be used to represent multi-side conflicts
