### ISSUE TITLE
Global .gitignore not respected

### ISSUE THREAD

**Issue by arxanas** [martinvonz/jj#87]
## Expected Behavior

`jj status` shows files which should be globally ignored:

```
$ jj status
...
A bin/.DS_Store
A tests/.DS_Store
```

## Actual Behavior

`jj status` should respect global `.gitignore` file by default.

## Steps to Reproduce the Problem

1. `git config --global core.excludesfile ~/.gitignore_global`
1. `jj init --git-repo=.`
1. `touch .DS_Store`
1. `jj st`

The same problem happens even if I create `~/.gitignore`.

## Specifications

- Version: jj 0.2.0 @ aadab1982dd7deaca7c20ba9d4c5e908115d7ba0
- Platform: macOS 11.6.4

**Comment by martinvonz** [comment]
I just found realized that `~/.gitignore` doesn't seem to be anywhere in Git's documentation of how ignores work, so I suspect I just hard-coded the location it happened to have on my system. Oops.

By the way, this bug is very closely related to #65, so I'll probably fix both at around the same time (but probably not the same commit).
