### ISSUE TITLE
REQUEST: Clean output option

### ISSUE THREAD

**Issue by xxxserxxx** [martinvonz/jj#931]
## Description

A feature to disable the non-ASCII, terminal colorization of output

While it's all very pretty, it makes it difficult to get clean output for (example) copying into issues. Control characters are currently printed even when piping output (when the output is _not_ a terminal), such as `more`. This makes scripting around jj more difficult.

A great option would be a global argument to disable pretty-printing. A good alternative would be to detect if the output isn't a terminal, and not pretty-print in that case. The latter is common behavior in command-line tooling.

### Edit

For anyone landing here, a workaround that works for many cases is to pipe output of programs that generate terminal control characters through:

```
sed 's/[^[:print:]]\[[^a-zA-Z]*[a-zA-Z]//g'
```

**Comment by martinvonz** [comment]
The colorization should only happen when writing to a terminal. Maybe you have set `ui.color = "always"` in your `~/.jjconfig.toml` (or `$XDG_CONFIG_HOME/jj/config.toml`)?

Which version are you running? Since 0.6.0, we have built-in support for pager. That should also be disabled when stdout is a not a terminal. I may still be worth upgrading to see if that changes anything.

> A great option would be a global argument to disable pretty-printing.

You can set `ui.color = "never"` to not get color. There's no config for getting more machine-readable output in general.

> A good alternative would be to detect if the output isn't a terminal, and not pretty-print in that case. The latter is common behavior in command-line tooling.

I don't know why that isn't working for you. Hopefully it's just that you have that `ui.color = "always"` setting enabled.
