### ISSUE TITLE
Branch is immediately conflicted upon `jj init --git-repo=.`

### ISSUE THREAD

**Issue by arxanas** [martinvonz/jj#934]
## Description

As discussed at https://discord.com/channels/968932220549103686/968932220549103689/1055292544608645220. This was the sequence of steps:

```
$  jj st
Error: There is no jj repo in "."
Hint: It looks like this is a git repo. You can create a jj repo backed by it by running this:
jj init --git-repo=.

$  jj init --git-repo=.
Initialized repo in "."

$  jj log
@ 2b5bfbd6de6a me@waleedkhan.name 2022-12-21 18:59:33.000 -06:00 d43ddbf1b884
| (no description set)
| o c9c47d2a677b me@waleedkhan.name 2022-12-21 12:09:31.000 -06:00 arxanas/solve? 791aea1e638d
| | temp: more day 19
| o 80344c9b99e8 me@waleedkhan.name 2022-12-19 18:34:15.000 -06:00 763fb4d34969
| | temp: more
| o 0bd33379cbb9 me@waleedkhan.name 2022-12-19 18:13:23.000 -06:00 796d4b7389b3
| | temp: day 19
o | 9cae61adbb93 me@waleedkhan.name 2022-12-21 18:56:44.000 -06:00 arxanas/y22d20 HEAD@git 9b1f62b6de19
|/  Solve year 2022 day 20
o 15b22016de78 me@waleedkhan.name 2022-12-21 14:07:51.000 -06:00 main dab9ae6aebfb
~ Solve year 2022 day 21
```

As you can see, the `arxanas/solve?` branch, which existed previously in the Git repo, is conflicted on the very first invocation of `jj log`. There's only one Git remote in this case, so this shouldn't happen:

```
$ git remote -v
origin  git@github.com:arxanas/advent-of-code.git (fetch)
origin  git@github.com:arxanas/advent-of-code.git (push)
```

## Specifications

- Platform:

```
$  uname -a
Darwin waleedkhan.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
```

- Version: It might be a version of jj built from source.

```
$  jj version
jj 0.5.1
```

**Comment by martinvonz** [comment]
As we discussed on Discord, the problem here was that `refs/head/arxanas/solve` and `refs/remotes/origin/arxanas/solve` were siblings, not ancestor/descendant. On import, jj sees the two different targets and tries to merge them both to the `arxanas/solve` branch (which initially doesn't exist). So it applies one of them and that succeeds (non-existent + (abc123 - non-existent) => abc123). Then it tries to apply the second one, which results in a conflict (abc123 + (def456 - non-existent) => conflict).
